[package]
name = "qoe_cli_runner"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
serde = "1.0.219"
clap = { version = "4.4", features = ["derive"] }
qoe_core = { path = "../qoe-core" }